# Set matplotlib backend to avoid GUI issues
import matplotlib

matplotlib.use("Agg")

import xml.etree.ElementTree as ET
import numpy as np
import matplotlib.pyplot as plt
import os
from enum import Enum


# Wether to normalize sensitivity coefficients by max value or local value
class NormalizationType(Enum):
    MAX_VALUE = 0
    LOCAL_VALUE = 1
    NONE = 2


# Wether to order by max peak or area under curve
class OrderingType(Enum):
    MAX_PEAK = 0
    AREA_UNDER_CURVE = 1


#### Configuration ####
"""
Perform sensitivity analysis on the output XML files generated by BioSMOKE TGA simulations.
Generates plots of sensitivity coefficients for a target species and highlights the top N reactions.
This section allows users to configure parameters for the analysis.
"""

## File paths and parameters
target_species = "CO"  # Target species for sensitivity analysis
outputFolder = os.path.join("..", "TGA", "Output")  # Folder containing output XML files
number_of_top_reactions = 20  # Number of top reactions to plot

## Normalization
# Recommended to use MAX_VALUE of M_i for normalization to avoid issues at low concentrations
normalization_type = NormalizationType.MAX_VALUE
# Optionally normalize sensitivity coefficients using the highest value of the sensitivity coefficients
normalize = False

## Ordering
# MAX_PEAK: Order by maximum peak sensitivity value
# AREA_UNDER_CURVE: Order by area under the sensitivity curve
# Recommended to use MAX_PEAK
ordering_type = OrderingType.MAX_PEAK

#######################

sensitivity_child_file = os.path.join(
    outputFolder, f"Sensitivities.{target_species}.xml"
)
sensitivity_parent_file = os.path.join(outputFolder, "Sensitivities.xml")


def XmlTagToArray(root, tagName):
    if root.find(tagName) is None:
        raise ValueError(f"Tag '{tagName}' not found in the XML.")
    lines = root.find(tagName).text.strip().split("\n")
    data = []
    for line in lines:
        values = list(line.strip().split())
        data.append(values)
    return data


# Load the parent Sensitivity XML file
sensitivity_parent_root = ET.parse(sensitivity_parent_file).getroot()
parameters = np.array(
    XmlTagToArray(sensitivity_parent_root, "constant-parameters")
).astype(float)
number_of_parameters = np.array(
    XmlTagToArray(sensitivity_parent_root, "n-parameters")
).astype(int)[0, 0]
assert parameters.shape[0] == number_of_parameters, "Mismatch in number of parameters."

# Load the child Sensitivity XML file for the target species
sensitivity_child_root = ET.parse(sensitivity_child_file).getroot()
sensitivity_data = np.array(
    XmlTagToArray(sensitivity_child_root, "coefficients")
).astype(float)

# Load the Output XML file to get time points
output_root = ET.parse(os.path.join(outputFolder, "Output.xml")).getroot()
output_data = np.array(XmlTagToArray(output_root, "profiles")).astype(float)

species_index = np.array(XmlTagToArray(output_root, "mass")[1:])
temp = np.where(species_index[:, 0] == target_species)[0][0]
target_species_index = int(species_index[temp, -1]) - 2  # Adjust for 0-based indexing
print(f"Target species '{target_species}' found in Output.xml")

target_species_profile = output_data[:, target_species_index]
time_points = output_data[:, 0]  # the first column is time

# Normalize sensitivity coefficients
if normalization_type == NormalizationType.MAX_VALUE:
    print("Normalizing by max value...")
    max_value = np.max(target_species_profile)
    if max_value < 1e-20:
        raise ValueError(
            "Max value of target species profile is too small for normalization."
        )
    normalized_sensitivities = sensitivity_data * parameters.T / max_value
elif normalization_type == NormalizationType.LOCAL_VALUE:
    print("Normalizing by local value...")
    target_species_profile[target_species_profile < 1e-10] = 1e-10

    normalized_sensitivities = (
        sensitivity_data * parameters.T / target_species_profile[:, np.newaxis]
    )
elif normalization_type == NormalizationType.NONE:
    print("No normalization applied to sensitivity coefficients.")
    normalized_sensitivities = sensitivity_data

# Calculate coefficents
if OrderingType.MAX_PEAK:
    print("Calculating ordering by max peak...")
    max_peaks = np.max(normalized_sensitivities, axis=0)
    min_peaks = np.min(normalized_sensitivities, axis=0)
    ordering_values = np.where(
        np.abs(max_peaks) >= np.abs(min_peaks), max_peaks, min_peaks
    )

    # normalize the peaks by the max peak
    if normalize:
        ordering_values /= np.max(np.abs(ordering_values))
elif OrderingType.AREA_UNDER_CURVE:
    print("Calculating ordering by area under curve...")
    ordering_values = np.trapz(normalized_sensitivities, x=time_points, axis=0)

    if normalize:
        ordering_values /= np.max(np.abs(ordering_values))

# Get the ordering of parameters
ordering = np.argsort(np.abs(ordering_values))[::-1]
# ordering = np.argsort(np.abs(ordering_values))

reaction_indexes = ordering + 1  # Reaction indices are 1-based

# Select top N reactions
N = min(
    number_of_top_reactions, len(ordering)
)  # Automatically limit N to available reactions
top_N_ordering = ordering[:N]
top_N_values = ordering_values[top_N_ordering]
top_N_reaction_indexes = top_N_ordering + 1

print(f"Plotting top {N} reactions out of {len(ordering)} total reactions")

# Create figure with dynamic sizing
fig_height = max(6, N * 0.4)  # Minimum height of 6 inches
fig, ax = plt.subplots(figsize=(10, fig_height))

# Create gradient colors based on magnitude
max_abs_value = abs(max(top_N_values))
min_abs_value = abs(min(top_N_values))
colors = []
for val in top_N_values:
    if val > 0:
        # Shades of blue (lighter to darker based on magnitude)
        intensity = abs(val) / max_abs_value
        colors.append((0.7 * (1 - intensity), 0.8 * (1 - intensity) + 0.2, 1.0))
    else:
        # Shades of red (lighter to darker based on magnitude)
        intensity = abs(val) / min_abs_value
        colors.append((1.0, 0.7 * (1 - intensity), 0.7 * (1 - intensity)))

# Plot horizontal bars
y_positions = np.arange(N)
bars = ax.barh(
    y_positions[::-1],
    top_N_values,
    height=0.7,
    color=colors,
    edgecolor="black",
    linewidth=0.5,
)

# Add thick vertical line at x=0
ax.axvline(x=0, color="black", linewidth=3, linestyle="-", zorder=3)

# Add reaction index text near each bar
max_abs_value = max(abs(top_N_values))
for i, (idx, value) in enumerate(zip(top_N_reaction_indexes, top_N_values)):
    if value > 0:
        x_pos = value + 0.01 * max_abs_value
        ha = "left"
    else:
        x_pos = value - 0.01 * max_abs_value
        ha = "right"

    ax.text(
        x_pos,
        N - 1 - i,
        f"R{idx}",
        va="center",
        ha=ha,
        fontsize=9,
        fontweight="bold",
    )

ax.set_yticks([])
ax.set_xlabel("Sensitivity Coefficient")
ax.set_title(f"Top {N} Reactions for Sensitivity of {target_species}")
ax.grid(axis="x", alpha=0.3, linestyle="--")
plt.tight_layout()
plt.savefig(f"Sensitivity_{target_species}.png", dpi=300, bbox_inches="tight")
